---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: myportofolio
  name: myportofolio
  namespace: my-portofolio
spec:
  lookupPolicy:
    local: false

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
    openshift.io/image.dockerRepositoryCheck: enabled
  labels:
    build: myportofolio
  name: myportofolio
  namespace: my-portofolio
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 16-alpine
      annotations:
        openshift.io/imported-from: node:16-alpine
      from:
        kind: DockerImage
        name: node:16-alpine
      generation: 2
      iconClass: icon-nodejs
      referencePolicy:
        type: Source
    - name: latest
      annotations:
        openshift.io/imported-from: node:latest
      from:
        kind: DockerImage
        name: node:latest
      generation: 2
      iconClass: icon-nodejs
      referencePolicy:
        type: Source
