---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: myportofolio
  name: myportofolio
  namespace: my-portofolio
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
    openshift.io/image.dockerRepositoryCheck: enabled
  labels:
    build: myportofolio
  name: alpine
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/imported-from: alpine:latest
      from:
        kind: DockerImage
        name: alpine:latest
      generation: 2
      name: latest
      referencePolicy:
        type: Source
