---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  tasks:
    - name: test-linter
      taskRef:
        name: test-linter
    - name: build-deploy
      taskRef:
        name: build-deploy
      runAfter:
        - test-linter
