apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-portofolio-deploy
  namespace: my-portofolio
spec:
  steps:
    - name: clone
      image: node
      script: |
        #!/bin/bash

        git clone https://gitlab.apps.cluster-hvt9q.hvt9q.sandbox1172.opentlc.com/fajjarnr/myportofolio.git /workspace/myportofolio

    - name: configure-project
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        #!/bin/bash

        set -euo pipefail

        cd /workspace/src/myportofolio
        oc apply -f imageStream.yaml
        oc apply -f buildConfig.yaml

    - name: build
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        #!/bin/bash

        set -euo pipefail

        oc start-build -F myportofolio -n my-portofolio

    - name: deploy
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        #!/bin/bash

        set -euxo pipefail

        cd /workspace/myportofolio/apps/gitops
        oc apply -f deployment.yaml

        BUILDDATE=$(date +%Y-%m-%d-%H%M%S)
        oc patch deployment myportofolio -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"last-build\":\"$BUILDDATE\"}}}}}"

        oc apply -f service.yaml
        oc apply -f route.yaml
